import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

export const exportStudentTestPdf = async (student, training, questions, answers) => {
  const prePct  = student.pre_max  > 0 ? Math.round((student.pre_score  / student.pre_max)  * 100) : 0;
  const postPct = student.post_max > 0 ? Math.round((student.post_score / student.post_max) * 100) : 0;

  // Build table rows
  const rows = questions.map((q, i) => {
    const ans   = answers.find(a => a.question_id === q.id);
    const isMCQ = q.question_type === 'mcq';

    let studentAnswer = 'No Answer';
    let result        = '—';
    let earned        = `— / ${q.points}`;

    if (ans) {
      if (isMCQ) {
        studentAnswer = ans.choices?.choice_text || 'No Answer';
        const isCorrect = !!ans.choices?.is_correct;
        result  = isCorrect ? '✓ Correct' : '✗ Wrong';
        earned  = `${isCorrect ? q.points : 0} / ${q.points}`;
      } else {
        studentAnswer = ans.answer_text || 'No Answer';
        result  = '—';
        earned  = ans.manual_score != null
          ? `${ans.manual_score} / ${q.points}`
          : `Ungraded / ${q.points}`;
      }
    }

    const rowBg = i % 2 === 0 ? '#ffffff' : '#f9fafb';
    return `
      <tr style="background:${rowBg}; border-bottom:1px solid #e5e7eb;">
        <td style="padding:10px 8px; font-size:12px; line-height:1.5;" dir="auto">
          <span style="color:#6b7280; font-size:10px; font-weight:600;">${isMCQ ? 'MCQ' : 'OPEN'}</span><br/>
          ${i + 1}. ${q.question_text}
        </td>
        <td style="padding:10px 8px; font-size:12px; color:#374151; line-height:1.5;" dir="auto">${studentAnswer}</td>
        <td style="padding:10px 8px; font-size:11px; text-align:center; font-weight:600;
          color:${result.includes('Correct') ? '#16a34a' : result.includes('Wrong') ? '#dc2626' : '#6b7280'};">
          ${result}
        </td>
        <td style="padding:10px 8px; font-size:12px; text-align:center; font-weight:700; color:#4f46e5;">
          ${earned}
        </td>
      </tr>`;
  }).join('');

  // Build the full HTML page
  const container = document.createElement('div');
  container.style.cssText = `
    position: fixed; left: -9999px; top: 0;
    width: 794px; background: white;
    font-family: 'Segoe UI', 'Tahoma', Arial, sans-serif;
    padding: 40px; color: #111827; box-sizing: border-box;
  `;

  container.innerHTML = `
    <div style="display:flex; align-items:center; gap:16px; border-bottom:3px solid #4f46e5; padding-bottom:18px; margin-bottom:24px;">
      <div>
        <div style="font-size:11px; color:#6b7280; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:4px;">TGH Trainings Center</div>
        <h1 style="margin:0; font-size:20px; color:#4f46e5;">Test Results</h1>
        <h2 style="margin:4px 0 0; font-size:15px; color:#1f2937;" dir="auto">${training.title}</h2>
      </div>
    </div>

    <div style="display:grid; grid-template-columns:1fr 1fr; gap:12px; background:#f3f4f6; border-radius:10px; padding:18px; margin-bottom:24px;">
      <div>
        <div style="font-size:10px; color:#9ca3af; margin-bottom:3px; text-transform:uppercase; letter-spacing:0.05em;">Student Name</div>
        <div style="font-size:14px; font-weight:600;" dir="auto">${student.user_name}</div>
      </div>
      <div>
        <div style="font-size:10px; color:#9ca3af; margin-bottom:3px; text-transform:uppercase; letter-spacing:0.05em;">Phone</div>
        <div style="font-size:14px;">${student.phone}</div>
      </div>
      <div>
        <div style="font-size:10px; color:#9ca3af; margin-bottom:3px; text-transform:uppercase; letter-spacing:0.05em;">Pre-Test Score</div>
        <div style="font-size:16px; font-weight:700; color:#4f46e5;">${student.pre_score} / ${student.pre_max} <span style="font-size:12px; color:#6b7280;">(${prePct}%)</span></div>
      </div>
      <div>
        <div style="font-size:10px; color:#9ca3af; margin-bottom:3px; text-transform:uppercase; letter-spacing:0.05em;">Post-Test Score</div>
        <div style="font-size:16px; font-weight:700; color:#4f46e5;">${student.post_score} / ${student.post_max} <span style="font-size:12px; color:#6b7280;">(${postPct}%)</span></div>
      </div>
    </div>

    <table style="width:100%; border-collapse:collapse; border:1px solid #e5e7eb; border-radius:8px; overflow:hidden;">
      <thead>
        <tr style="background:#4f46e5; color:white;">
          <th style="padding:10px 8px; text-align:left;  font-size:12px; width:38%;">Question</th>
          <th style="padding:10px 8px; text-align:left;  font-size:12px; width:36%;">Student Answer</th>
          <th style="padding:10px 8px; text-align:center;font-size:12px; width:13%;">Result</th>
          <th style="padding:10px 8px; text-align:center;font-size:12px; width:13%;">Points</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>

    <div style="margin-top:20px; font-size:10px; color:#9ca3af; text-align:center;">
      Generated by TGH Trainings Center · ${new Date().toLocaleDateString()}
    </div>
  `;

  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, { scale: 2, useCORS: true, logging: false });
    const imgData = canvas.toDataURL('image/png');

    const pdf      = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageW    = pdf.internal.pageSize.getWidth();
    const pageH    = pdf.internal.pageSize.getHeight();
    const imgH     = (canvas.height * pageW) / canvas.width;

    let yLeft = imgH;
    let yPos  = 0;
    pdf.addImage(imgData, 'PNG', 0, yPos, pageW, imgH);
    yLeft -= pageH;

    while (yLeft > 0) {
      yPos = yLeft - imgH;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, yPos, pageW, imgH);
      yLeft -= pageH;
    }

    pdf.save(`Test_Results_${(student.user_name || 'student').replace(/\s+/g, '_')}.pdf`);
  } finally {
    document.body.removeChild(container);
  }
};
